### ISSUE TITLE
Camera1 start failed runtime exception when starting video recording

### ISSUE THREAD

**Issue by alez007** [CameraKit/camerakit-android#109]
Hi, 

Currently on my samsung galaxy s4, using front camera only, the video recording fails with:
`Caused by: java.lang.RuntimeException: start failed.
                                                                                   at android.media.MediaRecorder.start(Native Method)
                                                                                   at com.flurgle.camerakit.Camera1.startVideo(Camera1.java:240)
                                                                                   at com.flurgle.camerakit.CameraView.startRecordingVideo(CameraView.java:322)`

any solutions for this ? 

Thank you

**Comment by passos** [comment]
+1 same problem.

**Comment by tsoumalis** [comment]
This happens for me also. Any progress on this? After some research I have found that maybe the cause of this is a difference in preview size and actual video recording size. Unfortunately I don't own a device where I can reproduce this and try to solve it but I have received multiple crash reportings from S4 and S7 Edge.
