### ISSUE TITLE
start() causes a crash on HTC devices

### ISSUE THREAD

**Issue by rencsaridogan** [CameraKit/camerakit-android#213]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://github.com/wonderkiln/CameraKit-Android/.github/CONTRIBUTING.md)?

Yes

### Environment

Brand: HTC
Device: Various Devices
OS: Marshmallow (6.0)

### Steps to Reproduce

1. App opens
2. App redirects to the Activity where CameraKit is used
3. App crashes
### Expected Behavior

App not to crash.

### Actual Behavior

CameraKit causes a crash.

### Reproducible Demo

Library issue, basic demo is just using CameraKit, nothing special.

### Stacktrace

```
Fatal Exception: java.lang.RuntimeException: startPreview failed
       at android.hardware.Camera._startPreview(Camera.java)
       at android.hardware.Camera.startPreviewSubCam(Camera.java:1071)
       at android.hardware.Camera.startPreview(Camera.java:1084)
       at com.wonderkiln.camerakit.Camera1.start(Camera1.java:117)
       at com.wonderkiln.camerakit.CameraView$3.run(CameraView.java:313)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by emersoncloud** [comment]
I just put a comment on your other issue. Can you try and replicate on #318? Let me know if not, and I can reOpen this.
