### ISSUE TITLE
Crash on screen dim on Motorola X

### ISSUE THREAD

**Issue by Diederikjh** [CameraKit/camerakit-android#241]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes, mostly.

### Environment

Android studio 2.3.1 (running on Ubuntu) Build tools 27.0.1 Target SDK : 27
Camera kit version: 0.12.1-snapshot (as of 14 Nov 2017)
Seeing this on Motorola Moto X Force device. XT1580

### Steps to Reproduce

1. Launch test app as linked below
2. Leave device in portrait mode for a while.
3. When screen starts to dim, but isn't off yet, touch screen, to wake device up.
4. Preview is now not updating anymore.
5. Changing orientation, or taking a photo in this state will crash device.

This was also reproduced with the camerakit demo app from the Playstore.

Logcat snippet from orientation crash:

```
11-14 11:55:18.178 5621-5621/? D/AndroidRuntime: Shutting down VM
11-14 11:55:18.194 5621-5621/? E/AndroidRuntime: FATAL EXCEPTION: main
     Process: com.honeybeeapp.camerakittesting, PID: 5621
     java.lang.RuntimeException: set display orientation failed
         at android.hardware.Camera.setDisplayOrientation(Native Method)
         at com.wonderkiln.camerakit.Camera1.setDisplayAndDeviceOrientation(Camera1.java:152)
         at com.wonderkiln.camerakit.CameraView$1.onDisplayOrDeviceOrientationChanged(CameraView.java:155)
         at com.wonderkiln.camerakit.DisplayOrientationDetector.dispatchOnDisplayOrDeviceOrientationChanged(DisplayOrientationDetector.java:92)
         at com.wonderkiln.camerakit.DisplayOrientationDetector$1.onOrientationChanged(DisplayOrientationDetector.java:65)
         at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
         at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:699)
         at android.os.MessageQueue.nativePollOnce(Native Method)
         at android.os.MessageQueue.next(MessageQueue.java:323)
         at android.os.Looper.loop(Looper.java:136)
         at android.app.ActivityThread.main(ActivityThread.java:6123)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
11-14 11:55:18.203 1208-6759/? W/ActivityManager:   Force finishing activity com.honeybeeapp.camerakittesting/.CameraKitActivity
11-14 11:55:18.222 1208-1237/? I/PowerManagerService: setInteractiveWhileDozingInternal - false
```

(Full log in this [gist](https://gist.github.com/Diederikjh/22acbcb2c6ec6b78043771bc173d37e6))

### Expected Behavior

App shows preview, even after screem dims.

### Actual Behavior

App crashes after screen dims, and user interacts with camera.

### Reproducible Demo

https://github.com/Diederikjh/camerakit-crash/tree/android-4.4-null-image

**Comment by Diederikjh** [comment]
I re-tested this crash with version 0.13.1 of the library, and the behaviour is a bit different:  The preview just stops, but the app no longer crashes. Also switching to another app, and back again, wakes up the preview. 

[Repo](https://github.com/Diederikjh/camerakit-crash) I tested on.
