### ISSUE TITLE
Tap to focus always force close on Galaxy J5

### ISSUE THREAD

**Issue by thaodersar** [CameraKit/camerakit-android#290]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment
Samsung Galaxy J5 (SM-J510FN)
Android 6.0 or 7.1.1
CameraKit 0.13.1

### Steps to Reproduce

Using tap to focus (with or without marker)

(Write your steps here:)

1. Touch on camera view to focus and wait

### Expected Behavior

Camera should focus properly

### Actual Behavior

After tap on camera view to focus, camera start to focus and then force close after 1,2 seconds.
You can check this log

95-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: dispatchAttachedToWindow
12-19 00:11:08.151 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x27 surface={isValid=true -1799974912} surfaceGenerationChanged=true
12-19 00:11:08.152 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -1799974912} hwInitialized=true
12-19 00:11:08.182 3195-3195/  D/SurfaceView: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][720,1280] result=0x7 surface={Surface(name=null)/@0xf98108b isValid=true -1818034176}
12-19 00:11:08.217 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=true -1799974912} surfaceGenerationChanged=false
12-19 00:11:08.225 3195-3195/  D/SurfaceView: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={Surface(name=null)/@0xf98108b isValid=true -1818032128}
12-19 00:11:08.247 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
12-19 00:11:08.247 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: MSG_WINDOW_FOCUS_CHANGED 1
12-19 00:11:08.247 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -1799974912}
12-19 00:11:08.250 3195-3195/  V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@f4b9568 nm :   ic=null
12-19 00:11:08.250 3195-3195/  I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-19 00:11:08.283 3195-3195/  D/InputTransport: Input channel constructed: fd=187
12-19 00:11:08.283 3195-3195/  D/InputTransport: Input channel destroyed: fd=84
12-19 00:11:08.298 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: MSG_RESIZED: frame=Rect(0, 0 - 720, 1280) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
12-19 00:11:08.631 3195-3195/  D/ : [1] 3.onEvent: camerakit onevent: 
12-19 00:11:08.631 3195-3195/  D/ : [1] 3.onError: camerakit onerror
12-19 00:11:08.632 3195-3195/  D/ : [1] 3.onEvent: camerakit onevent: 
12-19 00:11:08.657 3195-3195/  D/SurfaceView: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x21 surface={Surface(name=null)/@0xf98108b isValid=true -1818034176}
12-19 00:11:09.007 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: changeCanvasOpacity: opaque=true
12-19 00:11:09.016 3195-3195/  D/ : [1] MainActivity.onSaveInstanceState: onSaveInstanceState
12-19 00:11:09.041 3195-3195/  D/ViewRootImpl@d8b6fe4[MainActivity]: mHardwareRenderer.destroy()#1
12-19 00:11:09.051 3195-3195/  D/ViewRootImpl@d8b6fe4[MainActivity]: Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
12-19 00:11:09.413 3195-3195/  D/ : [1] 3.onEvent: camerakit onevent: 
12-19 00:11:09.837 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: changeCanvasOpacity: opaque=false
12-19 00:11:10.442 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: ViewPostImeInputStage processPointer 0
12-19 00:11:10.508 3195-3195/  D/ViewRootImpl@3e555f0[LiveCameraActivity]: ViewPostImeInputStage processPointer 1
12-19 00:11:10.555 3195-3195/  D/ : [1] 3.onEvent: camerakit onevent: 
12-19 00:11:13.209 3195-3418/  V/FA: Inactivity, disconnecting from the service
12-19 00:11:15.141 3195-3195/  D/AndroidRuntime: Shutting down VM
12-19 00:11:15.142 3195-3195/  E/UncaughtException: java.lang.RuntimeException: setParameters failed
                                                                         at android.hardware.Camera.native_setParameters(Native Method)
                                                                         at android.hardware.Camera.setParameters(Camera.java:1940)
                                                                         at com.wonderkiln.camerakit.Camera1$8.run(Camera1.java:1057)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6816)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
12-19 00:11:15.175 3195-3418/  V/FA: Connecting to remote service
12-19 00:11:15.179 3195-3418/  V/FA: Recording user engagement, ms: 7334
12-19 00:11:15.201 3195-3418/  V/FA: Connection attempt already in progress
12-19 00:11:15.406 3195-3195/  E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process:  , PID: 3195
                                                                  java.lang.RuntimeException: setParameters failed
                                                                      at android.hardware.Camera.native_setParameters(Native Method)
                                                                      at android.hardware.Camera.setParameters(Camera.java:1940)
                                                                      at com.wonderkiln.camerakit.Camera1$8.run(Camera1.java:1057)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6816)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)(Write what happened. Add screenshots!)

**Comment by austinkettner** [comment]
This should be resolved in #318
