### ISSUE TITLE
Fail to connect to camera

### ISSUE THREAD

**Issue by Mohammad-Zyadat** [CameraKit/camerakit-android#317]
Non-fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.(Camera.java:545)
       at android.hardware.Camera.open(Camera.java:385)
       at com.wonderkiln.camerakit.Camera1.openCamera(Unknown Source)
       at com.wonderkiln.camerakit.Camera1.start(Unknown Source)
       at com.wonderkiln.camerakit.CameraView$2.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by austinkettner** [comment]
Hi @Mohammad-Zyadat can you please follow the issue template? We will then reOpen this ticket.
