### ISSUE TITLE
Nexus 7 2012 crashes when opening camera

### ISSUE THREAD

**Issue by AdrianMetzner** [CameraKit/camerakit-android#330]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes

### Environment

Nexus 7 (Version 2012)

### Steps to Reproduce

1.  Start an activity with the camera view
     a.) Note that the camera has to be set to be set with `camerakit:ckFacing="front"` as the device does not have a back camera 
2.   start the camera in onResume as per docu

### Expected Behavior

Front Camera should be shown

### Actual Behavior

Preview starts but after a few (mabe one or two) seconds the app crashes with (anonymized) Stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: CameraViewWorker
Process: xxx.xxxx.xxxx, PID: XYZABC
java.lang.RuntimeException: setParameters failed
   at android.hardware.Camera.native_setParameters(Native Method)
   at android.hardware.Camera.setParameters(Camera.java:2015)
   at com.wonderkiln.camerakit.Camera1.setZoom(Camera1.java:295)
   at com.wonderkiln.camerakit.Camera1.adjustCameraParameters(Camera1.java:855)
   at com.wonderkiln.camerakit.Camera1.adjustCameraParameters(Camera1.java:780)
   at com.wonderkiln.camerakit.Camera1.openCamera(Camera1.java:671)
   at com.wonderkiln.camerakit.Camera1.start(Camera1.java:124)
   at com.wonderkiln.camerakit.CameraView$2.run(CameraView.java:267)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:154)
   at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by emersoncloud** [comment]
Hey @AdrianMetzner could you test this on our latest release v1.0.0-beta3.1 from the v1.0.0 branch. Let me know if this issue persists and I'll reopen the ticket. Thanks!
