### ISSUE TITLE
startPreviewFailed error on 0.13.1

### ISSUE THREAD

**Issue by rohanjain1** [CameraKit/camerakit-android#332]
Hi, 
I'v recently integrated cameraKit into my application and receiving crash reports: 

Fatal Exception: java.lang.RuntimeException: startPreview failed
       at android.hardware.Camera.startPreview(Camera.java)
       at com.wonderkiln.camerakit.Camera1.start(Camera1.java:128)
       at com.wonderkiln.camerakit.CameraView$2.run(CameraView.java:266)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.os.HandlerThread.run(HandlerThread.java:61)

One of the users is using a Redmi Note 4 and says that the issue is happening contiuously on his device.
All permissions are granted.
We released an update last night and after the update the app was working fine on his device. However, today morning it's consistently crashing out with this error.

**Comment by emersoncloud** [comment]
Hi @rohanjain1 we are working hard on version 1.0.0 which includes many fixes and refactors of the codebase. Could you test your application on the latest PR #318? Let me know if you run into any issues!
