### ISSUE TITLE
Add CameraKit functions

### ISSUE THREAD

**Issue by austinkettner** [CameraKit/camerakit-android#386]
.getBitmap();
CameraKitView.stop();
CameraKitView.start();

Official Maintainer Ticket.

**Comment by emersoncloud** [comment]
From @polppol on the PR: 

replace `stop()` with  `onPause() ` work fine
but when I call `onResume()` it just crashed 

> java.lang.NullPointerException: Attempt to invoke virtual method 'int com.camerakit.CameraKitView$Size.getWidth()' on a null object reference
>         at com.camerakit.CameraKitView$Camera2$1$7.run(CameraKitView.java:1844)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.os.HandlerThread.run(HandlerThread.java:65)

EDIT: Only crashed if captureImage() is called right after onResume()
