### ISSUE TITLE
Can't take picture continuously  in version 1.0.0-beta3.1 

### ISSUE THREAD

**Issue by iboomboom** [CameraKit/camerakit-android#399]
### Is this a bug report?
YES
(write your answer here)
Cant take picture continuously in version 1.0.0-beta3.1,
If i click the camera button crazy,it has a bug.Please see the log.

###Logcat
Process: com.camerakit.app, PID: 22823
    java.lang.RuntimeException: takePicture failed, error=-38
        at android.hardware.Camera.native_takePicture(Native Method)
        at android.hardware.Camera.takePicture(Camera.java:1772)
        at android.hardware.Camera.takePicture(Camera.java:1705)
        at com.camerakit.api.camera1.Camera1.capturePhoto(Camera1.kt:137)
        at com.camerakit.api.ManagedCameraApi.capturePhoto(ManagedCameraApi.kt:46)
        at com.camerakit.CameraPreview.capturePhoto(CameraPreview.kt:189)
        at com.camerakit.CameraKitView.captureImage(CameraKitView.java:485)
        at com.camerakit.app.MainActivity$5.onClick(MainActivity.java:182)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by emersoncloud** [comment]
@iboomboom Could you test on the latest version v1.0.0-beta3.9 and see if the issue persists? I'll reopen the issue if that's the case! Thanks!
