### ISSUE TITLE
NullPointerException while taking image

### ISSUE THREAD

**Issue by ShalevCohen2112** [CameraKit/camerakit-android#435]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setOneShotPreviewCallback(android.hardware.Camera$PreviewCallback)' on a null object reference
        at com.wonderkiln.camerakit.Camera1.captureImage(Camera1.java:452)
        at com.wonderkiln.camerakit.CameraView.captureImage(CameraView.java:461)
        at com.wonderkiln.camerakit.CameraView.captureImage(CameraView.java:441)
        at com.carmel.clientLibrary.CustomedViews.CustomCameraActivity.lambda$setListeners$0$CustomCameraActivity(CustomCameraActivity.java:56)
        at com.carmel.clientLibrary.CustomedViews.CustomCameraActivity$$Lambda$0.onClick(Unknown Source)
        at android.view.View.performClick(View.java:4799)
        at android.view.View$PerformClick.run(View.java:20042)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by emersoncloud** [comment]
Hi @ShalevCohen2112 can you provide some more details about your application and Android device? 

1. Which version of CameraKit you're using
2. The section of code you're using to create your CameraKitView 
3. Your Android device version

Once I get that information I'll be able to better diagnose your issue. Thanks!
