### ISSUE TITLE
Crashes on Android 5.1.1 emulator

### ISSUE THREAD

**Issue by prakaz** [CameraKit/camerakit-android#483]
The library (1.0.0-beta3.10) runs on Android 8,9 (emulators). But while testing on Emulator (Nexus 4 - Android 5.1.1, API 22), I get the following error 100% of the time: 

```
E/AndroidRuntime: FATAL EXCEPTION: CAMERA
    Process: com.xx.xx.xx, PID: 16547
    java.lang.RuntimeException
        at com.camerakit.api.camera2.Camera2.open(Camera2.kt:48)
        at com.camerakit.api.ManagedCameraApi.open(ManagedCameraApi.kt:12)
        at com.camerakit.CameraPreview.openCamera(CameraPreview.kt:234)
        at com.camerakit.CameraPreview$start$1$1.invokeSuspend(CameraPreview.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
        at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.camerakit.CameraPreview$start$1.invokeSuspend(CameraPreview.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by prakaz** [comment]
This was fixed by enabling the hardware camera of the computer from the AVD manager. 

> AVD manager > Actions - Edit this AVD > Show Advanced Settings > Camera - Back : YOUR_COMPUTER_CAMERA

**Comment by Hasiy** [comment]
出现问题的设备：GI-I9500_TMMARS    OS：5.1
还有 oppo A3,  MI2s  ,PADM00

`java.lang.RuntimeException
    at com.camerakit.api.camera2.a.a(Camera2.kt:48)
    at com.camerakit.api.f.a(ManagedCameraApi.kt:12)
    at com.camerakit.CameraPreview.a(CameraPreview.kt:234)
    at com.camerakit.CameraPreview$start$1$1.a(CameraPreview.kt:118)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.b(ContinuationImpl.kt:32)
    at kotlinx.coroutines.bc$a.b(Dispatched.kt:235)
    at kotlinx.coroutines.az.run(Dispatched.kt:81)
    at kotlinx.coroutines.bl.e(EventLoop.kt:123)
    at kotlinx.coroutines.g.j(Builders.kt:69)
    at kotlinx.coroutines.j.a(Builders.kt:45)
    at kotlinx.coroutines.i.a(Unknown Source)
    at kotlinx.coroutines.j.a(Builders.kt:35)
    at kotlinx.coroutines.i.a(Unknown Source)
    at com.camerakit.CameraPreview$start$1.a(CameraPreview.kt:115)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.b(ContinuationImpl.kt:32)
    at kotlinx.coroutines.bc$a.b(Dispatched.kt:235)
    at kotlinx.coroutines.az.run(Dispatched.kt:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)`
