### ISSUE TITLE
Crash on start if add ndk abiFilters armeabi

### ISSUE THREAD

**Issue by AnyLifeZLB** [CameraKit/camerakit-android#484]
when add ndk filter config
    defaultConfig {
        multiDexEnabled true

        ndk {
            abiFilters 'armeabi'           
        }
    }
in build.gradle file ,App crash on start. here is the error message.

        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.camerakit.CameraKitView
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.camerakit.CameraKitView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.lebang.activity.camera.TestCameraActivity.onCreate(TestCameraActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file 

"/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/base.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_resources_apk.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.vanke.wyguide-JJ4gWBbX-WtdzNu_oRvwlg==/split_lib_slice_3_apk.apk", zip file

**Comment by AnyLifeZLB** [comment]
remove ndk filter will work fine.

**Comment by sayhellotogithub** [comment]
I need armeabi, how to solve the problem
