### ISSUE TITLE
java.lang.IllegalStateException: CameraDevice was already closed

### ISSUE THREAD

**Issue by Hasiy** [CameraKit/camerakit-android#529]
### Environment
Redmi 3S   6.0.1   关闭相机后 又迅速打开。
### Actual Behavior  
java.lang.IllegalStateException: CameraDevice was already closed
	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1997)
	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:623)
	at com.camerakit.api.camera2.a.k(Camera2.kt:193)
	at com.camerakit.api.camera2.a.a(Camera2.kt:152)
	at com.camerakit.api.f.a(ManagedCameraApi.kt:51)
	at com.camerakit.CameraPreview$capturePhoto$1$1.a(CameraPreview.kt:158)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.b(ContinuationImpl.kt:32)
	at kotlinx.coroutines.bc$a.b(Dispatched.kt:235)
	at kotlinx.coroutines.az.run(Dispatched.kt:81)
	at kotlinx.coroutines.bl.e(EventLoop.kt:123)
	at kotlinx.coroutines.g.j(Builders.kt:69)
	at kotlinx.coroutines.j.a(Builders.kt:45)
	at kotlinx.coroutines.i.a(Unknown Source)
	at kotlinx.coroutines.j.a(Builders.kt:35)
	at kotlinx.coroutines.i.a(Unknown Source)
	at com.camerakit.CameraPreview$capturePhoto$1.a(CameraPreview.kt:156)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.b(ContinuationImpl.kt:32)
	at kotlinx.coroutines.bc$a.b(Dispatched.kt:235)
	at kotlinx.coroutines.az.run(Dispatched.kt:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by liujingyou** [comment]
On Android P，this bug often happens
