### ISSUE TITLE
Facing issue in OnePlus device

### ISSUE THREAD

**Issue by KaviIDPal** [CameraKit/camerakit-android#551]
### Is this a bug report?

Yes

Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:727)
       at android.hardware.Camera.open(Camera.java:523)
       at com.wonderkiln.camerakit.Camera1.openCamera(Camera1.java:486)
       at com.wonderkiln.camerakit.Camera1.start(Camera1.java:114)
       at com.wonderkiln.camerakit.CameraView$3.run(CameraView.java:313)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

### Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

Yes

### Environment

(Please include the following information along with any other relevant environment details.)

CameraKit Version: 0.11.2

Android Device: ONEPLUS A3003

Android Version: 8

### Steps to Reproduce

(Write your steps here:)

1. While opening camera
2. App get crashed

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

(Include your CameraKit setup and usage.)

**Comment by pradipvaghasiya** [comment]
Did u find solution/workaround?
