### ISSUE TITLE
couldn't find "libyuvOperator.so"

### ISSUE THREAD

**Issue by m404056626** [CameraKit/camerakit-android#565]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.csrcb.ummp-1/base.apk"],nativeLibraryDirectories=[/data/user/0/com.csrcb.ummp/app_plugins_lib, /data/app/com.csrcb.ummp-1/lib/arm, /system/fake-libs, /data/app/com.csrcb.ummp-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]] couldn't find "libyuvOperator.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1533)
        at com.wonderkiln.camerakit.JpegTransformer.<clinit>(JpegTransformer.java:44)
        at com.wonderkiln.camerakit.PostProcessor.getJpeg(PostProcessor.java:36)
        at com.wonderkiln.camerakit.CameraView$4.imageCaptured(CameraView.java:470)
        at com.wonderkiln.camerakit.Camera1$5.onPictureTaken(Camera1.java:429)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1185)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by peterfortuin** [comment]
I seem to have to same issue.
